# site settings
title: AAziz & Co. Accountants and Tax Consultants
email: info@aazizandco.co.uk
secondary_email: staff@aazizandco.co.uk
description: This is official jekyll template for bootstrap 5 by Brianloggers.
socials:
  phone: +44 203 6599 254
  whatsapp: +44 781 0448 530
  whatsapp2: +44 739 2438 213
  facebook: AAzizandco
  instagram: aazizandco_uk
  twitter: AazizTax
  gmb: aazizandco
  youtube:
  trustpilot: AAziz
  soundcloud:
  spotify:
address:
  street: 2- Sanders Parade, Greyhound Lane,
  city: Streatham,
  state: London,
  country: UK,
  post_code: SW16 5NL

baseurl: "" # the subpath of your site, e.g. /blog
url: https://xhifi.github.io/aaziz-site/ # the base hostname & protocol for your site

author:
  youtube:
  facebook:
  github:
  instagram:
  twitter:

# build settings
markdown: kramdown

exclude:
  - "*.gemspec"
  - LICENSE.md
  - CONTRIBUTING.md
  - README.md

sass:
  sass_dir: assets/dev/sass
  style: compressed
